### ISSUE TITLE
Check behavior for maintainers and admins

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective-bot#49]
While working on the documentation, we need to double check the behavior for maintainers and admins. In the [Readme](README.md), it's currently written:

> Note that the Open Collective Bot won't comment on issues opened by maintainers or other admins of your Collective.

I could not verify that behavior by reading the code or tests. If this is confirmed, we need to support that. 

@maticzav can you provide your input?

**Comment by Betree** [comment]
I can confirm that the bot doesn't detect:
- That I'm an admin of the collective on OC
- That I'm a member of the organization on Github

See https://github.com/CaptainFact/captain-fact/issues/83

**Comment by maticzav** [comment]
Hey 👋,

Yeah, I see now. It's a "glitch" which wasn't supposed to come up in the release if I had stuck to the plan and dropped the `default` message. The problem is that @Betree in the example classifies as a non-backer due to https://github.com/opencollective/opencollective-bot/blob/18ec25b837b44b3c44da64d732904cf3d2bb6f2e/src/backers.ts#L24.

One possible solution that I see is dropping `backer-only` support and allow for further customisation based on role, or we could simply introduce a `null` return value which would classify as "members"/"backers" etc. = ignore.

I can submit a PR if you wish, however, I suggest we consider all the options and decide where the bot will evolve.

**Comment by znarf** [comment]
@maticzav The problem is that according to the Readme, admins of the collective should not get any messages. When looking at the data from https://opencollective.com/captainfact_io/members.json and the code from https://github.com/opencollective/opencollective-bot/blob/18ec25b837b44b3c44da64d732904cf3d2bb6f2e/src/backers.ts I don't see the intended mechanism that should prevent admins to receive messages. Could you explain that?

Also, I'm not sure I understand your `backer-only` point. Are you talking about backers without a tier?
